### PR TITLE
SCO-171 Tomcat startup error for missing type on AbstractSSPDataModel#mManaged

### PR DESCRIPTION
**Pull request by ern**

### CODE REVIEW

**Comment by ern** [comment]
I only verified that the startup error is no longer present.

**Comment by bjones86** [comment]
I think this only affects the 19.x branch, or have you seen it on master or 20 as well?

**Comment by ottenhoff** [comment]
It only affects 19.x AFAIK but seems like stronger typing is a plus

**Comment by bjones86** [comment]
Yup, agreed. I was just curious.

**Comment by bjones86** [comment]
Hmm looks like it doesn't build as is, but it's certainly unrelated to the changes here. @ern, do you have any other changes locally to get it to build?

**Comment by ottenhoff** [comment]
Okay I'm going to merge this into master then will work on a PR to fix the build (because of Apache Ignite changes in master)

**Pull request merged**
